POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkRhbiIsImlkIjoiNjJhZTJhNDdkYWRlNDc1YzE1YThlODExIiwiaWF0IjoxNjU1NTgxMjcwfQ.QDyAJC-mQcVPxUVWM_EJaz1iBoxqq4V_ujRhbSvLzrM

{
  "title": "Teaching Fullstack",
  "author": "Dan Sabelli",
  "url": "fullstackdan.com",
  "likes": 2,
  "userId": "62ac789076d378adbe5647aa"
}